#################################################################
# render.yaml                                           #
#################################################################

# List of all services
services:
  # A Dockerfile-based background worker
  - type: worker
    name: researcher
    runtime: docker
    dockerfilePath: ./Dockerfile # Optional
    # dockerContext: ./sub/src # Optional
    # branch: queue # Optional
