services:
  - type: web
    name: gpt-researcher
    env: docker
    plan: free  # Adjust according to your needs (e.g., free, standard, pro)
    dockerfilePath: ./Dockerfile  # Ensure your Dockerfile is correctly referenced
    envVars:
      - key: ${OPENAI_API_KEY}
      - key: ${TAVILY_API_KEY}
      - key: ${LANGCHAIN_API_KEY}
    ports:
      - port: 8000
    healthCheckPath: '/'  # Adjust according to your app's health check endpoint

  - type: web
    name: gptr-nextjs
    env: docker
    plan: free  # Adjust according to your needs (e.g., free, standard, pro)
    dockerfilePath: ./multi_agents/frontend/Dockerfile.dev  # Path to the Dockerfile for the frontend
    envVars:
      - key: CHOKIDAR_USEPOLLING
        value: true
    # volumes:
    #   - path: ./multi_agents/frontend
    #     mountPath: /app
    ports:
      - port: 3000
    healthCheckPath: '/'  # Adjust according to your app's health check endpoint
